{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tsuga-spicy-gremlin.fullname" . }}
  labels:
{{ include "tsuga-spicy-gremlin.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "tsuga-spicy-gremlin.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "tsuga-spicy-gremlin.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      {{- with .Values.podAnnotations }}
      annotations:
{{ toYaml . | indent 8 }}
      {{- end }}
    spec:
      automountServiceAccountToken: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
{{ toYaml . | indent 8 }}
      {{- end }}
      containers:
        - name: spicy-gremlin
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.securityContext }}
          securityContext:
{{ toYaml . | indent 12 }}
          {{- end }}
          env:
            - name: FLAGD_API_BASE_URL
              value: {{ .Values.env.flagdApiBaseUrl | quote }}
            - name: MIN_INTERVAL_SEC
              value: {{ .Values.env.minIntervalSec | quote }}
            - name: MAX_INTERVAL_SEC
              value: {{ .Values.env.maxIntervalSec | quote }}
            - name: REQUEST_TIMEOUT_SEC
              value: {{ .Values.env.requestTimeoutSec | quote }}
            - name: MAX_ACTIVE_FLAGS
              value: {{ .Values.env.maxActiveFlags | quote }}
            - name: RUN_ON_START
              value: {{ .Values.env.runOnStart | quote }}
            - name: DRY_RUN
              value: {{ .Values.env.dryRun | quote }}
            - name: WARN_UNKNOWN_FLAGS
              value: {{ .Values.env.warnUnknownFlags | quote }}
            - name: FLAG_SCHEMA
              value: {{ .Values.env.flagSchema | quote }}
            {{- if .Values.env.randomSeed }}
            - name: RANDOM_SEED
              value: {{ .Values.env.randomSeed | quote }}
            {{- end }}
            {{- if .Values.env.offDefaultsJson }}
            - name: OFF_DEFAULTS_JSON
              value: {{ .Values.env.offDefaultsJson | quote }}
            {{- end }}
            {{- if .Values.env.scenariosJson }}
            - name: SCENARIOS_JSON
              value: {{ .Values.env.scenariosJson | quote }}
            {{- end }}
            {{- with .Values.extraEnv }}
{{ toYaml . | indent 12 }}
            {{- end }}
          {{- with .Values.resources }}
          resources:
{{ toYaml . | indent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
{{- end }}
