agent:
  config:
    service:
      pipelines:
        extraPipelines:
          metrics/extra:
            receivers:
              - hostmetrics
            exporters:
              - otlphttp/tsuga
