{{- if .Values.serviceAccount.create -}}
{{- include "opentelemetry-kube-stack.validateResourceNames" . }}
{{- $helmAnnotations := dict "meta.helm.sh/release-name" .Release.Name "meta.helm.sh/release-namespace" .Release.Namespace }}
{{- $userAnnotations := .Values.serviceAccount.annotations | default dict }}
{{- $annotations := merge $userAnnotations $helmAnnotations }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opentelemetry-kube-stack.serviceAccountName" . }}
  labels:
    {{- include "opentelemetry-kube-stack.componentLabels" (dict "component" "serviceaccount" "Values" .Values "Release" .Release "Chart" .Chart) | nindent 4 }}
  {{- if $annotations }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
{{- end }}
