# yaml-language-server: $schema=../../values.schema.json
agent:
  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib
  collectLogs: false
  customConfig:
    receivers:
      custom-receiver: {}
    processors:
      custom-processor: {}
    exporters:
      custom-exporter: {}
    extensions:
      custom-extension: {}
    connectors:
      custom-connector: {}
    service:
      pipelines:
        logs:
          receivers:
            - custom-receiver
          processors:
            - custom-processor
          exporters:
            - custom-exporter
        metrics:
          receivers:
            - custom-receiver
          processors:
            - custom-processor